Allow named sections after numpy examples
mkdocstrings/griffe pull request #54
Opened 2022-02-24 07:27 UTC by FasterSpeeding

This is an attempt at fixing the current behaviour where numpydoc `Examples` sections would erroneously include the content of any following named sections until they reach an unnamed section or the end of the docstring.

2022-02-24 18:26 UTC, pawamoy requested changes
Nice, thanks! Could you simplify the test by reducing the size of the examples section, and by actually testing that first section is examples and second section is parameters? No need to check the examples section contents.

2022-02-24 21:11 UTC, FasterSpeeding commented
> Nice, thanks! Could you simplify the test by reducing the size of the examples section, and by actually testing that first section is examples and second section is parameters? No need to check the examples section contents.

Have updated the test 👍

2022-02-26 13:01 UTC, pawamoy commented
Thank you for updating the PR, I had to fix the tests because they were racing :sweat_smile: Sorry for the extra work.

2022-02-26 13:10 UTC, pawamoy commented
Just a minor quality warning left! 

> tests/test_docstrings/test_numpy.py:386:1: DAR101 Missing parameter(s) in Docstring: - parse_numpy

2022-02-26 13:11 UTC, pawamoy commented on tests/test_docstrings/test_numpy.py
> +    """Parse examples section."""
```suggestion
    """Parse examples section.

    Parameters:
        parse_numpy: Parse function (fixture).
    """
```

2022-02-26 21:29 UTC, merged

2022-02-27 08:58 UTC, FasterSpeeding commented
> Thank you for updating the PR, I had to fix the tests because they were racing 😅 Sorry for the extra work.

Np, just glad i could help 😄