feat: warn if docstring has extra parameters
mkdocstrings/griffe pull request #63
Opened 2022-04-08 14:15 UTC by KevinMusgrave

Reference: https://github.com/mkdocstrings/mkdocstrings/issues/408

2022-04-08 20:29 UTC, pawamoy requested changes
Hey, thanks a lot!

A few suggestions. We also must pass `warn_unknown_params=False` from `_read_other_parameters`, and add a test to make sure "Other Parameters" sections will not emit warnings.

2022-04-08 20:29 UTC, pawamoy commented on src/griffe/dataclasses.py
> +        return item in self._parameters_dict
```suggestion
    def __contains__(self, param_name: str):
        return param_name in self._parameters_dict
```

2022-04-08 20:29 UTC, pawamoy commented on src/griffe/docstrings/google.py
> +                    f'The docstring for {docstring.parent} contains "{name}" as a parameter, but "{name}" is not an argument.',
```suggestion
                    f"Parameter '{name}' does not appear in the parent signature",
```

2022-04-08 20:29 UTC, pawamoy commented on tests/test_docstrings/test_google.py
> +    )
```suggestion
    assert "'x' does not appear in parent signature" in warnings[1]
```

2022-04-09 00:33 UTC, KevinMusgrave commented
I added ```warn_unknown_params=False``` and tested for it in ```test_extra_parameter```

2022-04-09 10:35 UTC, pawamoy commented
I've split the test in two, to make it more resilient to future possible changes in the warning string: we just check no warnings were emitted.

2022-04-09 10:39 UTC, pawamoy approved these changes
LGTM

2022-04-09 10:40 UTC, merged

2022-04-09 10:41 UTC, pawamoy commented
Thanks again!